### ISSUE TITLE
Building with Boost 1.61

### ISSUE THREAD

**Issue by manuelafm** [K-3D/k3d#22]
I had to patch to build with Boost 1.61 in Debian (apparently, "system" is needed now).

Patch attached, but it's very simplistic, and it's 
probably better to add conditionals depending on the version of Boost, etc.

[fix-ftbfs-boost1.61.patch.txt](https://github.com/K-3D/k3d/files/414314/fix-ftbfs-boost1.61.patch.txt)

**Comment by barche** [comment]
Thanks for the patch, I think this will work even with older versions, but I'm handling the previous issue first on my limited K-3D time.

**Comment by barche** [comment]
I've just applied this for all boost versions, the system library has been around for a long time so this shouldn't cause any issues now. Let me know if/when you need me to tag a new release if you need that for Debian.

**Comment by manuelafm** [comment]
Thanks Bart.

I included the fix as a patch, but as usual, it would be nice to have a "clean" upstream version.

There will be a freeze soon to start the bugfixing towards the next stable release, in less than two months.  So if you can make a stable release within that timeframe, perhaps with some other fixes, I will do my best to try to have it in time before the freeze.

**Comment by barche** [comment]
OK, I just did a release: https://github.com/K-3D/k3d/releases/tag/k3d-0.8.0.6. From now on, please use the github releases tab as the reference for the latest released version.

**Comment by manuelafm** [comment]
This is fixed for many months now, closing it.  Thanks for the fix!
