### ISSUE TITLE
Disabling gnome-vfs, using gvfs or glib/gio?

### ISSUE THREAD

**Issue by manuelafm** [K-3D/k3d#28]
Hi,

In Debian we want to drop the dependency on gnome-vfs.  As the following bug report discusses, perhaps it is possible to substitute it by gvfs or glib/gio?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868394

> No gnome-vfs and gvfs are not compatible, but...
>
> Quickly looking at the code k3d seems to only use gnome-vfs to identify 
> mime-types and start the default associated application, this 
> functionality is now provided by the glib/gio, see:
>
> https://developer.gnome.org/gio/stable/GFileInfo.html
> https://developer.gnome.org/gio/stable/gio-GContentType.html
> https://developer.gnome.org/gio/stable/GAppInfo.html
> https://developer.gnome.org/gio/stable/GAppInfo.html#g-app-info-launch-default-for-uri
> https://stackoverflow.com/questions/1629172/how-do-you-get-the-icon-mime-type-and-application-associated-with-a-file-in-th/2170880#2170880
> https://stackoverflow.com/questions/6143100/how-do-i-open-a-file-in-its-default-program-linux/11623712#11623712

**Comment by barche** [comment]
OK, I'll take a look at updating the plugin to use GIO, seems like it's not much work.

**Comment by barche** [comment]
Should be done now, can you please check if this works as expected on Debian?

**Comment by manuelafm** [comment]
Thanks!

Will try hopefully tomorrow, if I happen to forget please ping me in a few days.

**Comment by manuelafm** [comment]
I cherry-picked the patch and release a new version in Debian with the change, everything seems to work fine.  Thanks a lot!
